name: temporal-pathrag
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.10
  - pip
  
  # ML/AI Stack
  - pytorch
  - torchvision
  - torchaudio
  - transformers
  - networkx
  
  # Data Science
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - jupyter
  
  # Basic utilities
  - requests
  - tqdm
  - pyyaml
  
  # Python packages via pip
  - pip:
      # Core RAG Libraries
      - faiss-cpu>=1.7.0
      - sentence-transformers>=2.2.0
      - langchain>=0.1.0
      - langchain-community>=0.0.20
      - langchain-core>=0.1.0
      - llama-index>=0.10.0
      
      # Training Libraries
      - accelerate>=0.24.0
      - bitsandbytes>=0.41.0
      - peft>=0.6.0
      
      # NLP Libraries
      - nltk>=3.8
      - spacy>=3.7.0
      
      # Development Tools
      - black>=23.0.0
      - flake8>=6.0.0
      - python-dotenv>=1.0.0
      - dataclasses-json>=0.6.0
      
      # Database Support
      - neo4j>=5.8.0
      - pymongo>=4.4.0
      
      # Additional ML Tools
      - datasets
      - huggingface-hub
      
      # Jupyter Extensions
      - ipywidgets
      - jupyterlab-widgets
      - widgetsnbextension
      - matplotlib-inline
      
      # Memory and Performance
      - psutil
      - gputil
      
      # Training Support
      - wandb
      
      # Additional utilities
      - click
      - rich
      - typer